import { VueConstructor } from 'vue'
import { VxeUIExport, VxeGlobalConfig } from './ui'

declare global {
  interface Window {
    VxeUI: VxeUIExport;
  }
}

export function install (app: VueConstructor, options?: VxeGlobalConfig): void

export type a = VueConstructor

export * from './ui'

// Components
export * from './components/alert'
export * from './components/anchor'
export * from './components/anchor-link'
export * from './components/breadcrumb'
export * from './components/breadcrumb-item'
export * from './components/button'
export * from './components/button-group'
export * from './components/calendar'
export * from './components/card'
export * from './components/carousel'
export * from './components/carousel-item'
export * from './components/checkbox'
export * from './components/checkbox-group'
export * from './components/col'
export * from './components/collapse'
export * from './components/collapse-pane'
export * from './components/countdown'
export * from './components/date-picker'
export * from './components/drawer'
export * from './components/flow-design'
export * from './components/flow-view'
export * from './components/form'
export * from './components/form-design'
export * from './components/form-gather'
export * from './components/form-item'
export * from './components/form-view'
export * from './components/icon'
export * from './components/icon-picker'
export * from './components/image'
export * from './components/image-group'
export * from './components/image-preview'
export * from './components/input'
export * from './components/layout-aside'
export * from './components/layout-body'
export * from './components/layout-container'
export * from './components/layout-footer'
export * from './components/layout-header'
export * from './components/link'
export * from './components/list-design'
export * from './components/list-view'
export * from './components/list'
export * from './components/loading'
export * from './components/menu'
export * from './components/modal'
export * from './components/number-input'
export * from './components/optgroup'
export * from './components/option'
export * from './components/pager'
export * from './components/password-input'
export * from './components/print-page-break'
export * from './components/print'
export * from './components/pulldown'
export * from './components/radio'
export * from './components/radio-button'
export * from './components/radio-group'
export * from './components/row'
export * from './components/select'
export * from './components/switch'
export * from './components/tab-pane'
export * from './components/tabs'
export * from './components/tag'
export * from './components/text'
export * from './components/textarea'
export * from './components/tip'
export * from './components/tooltip'
export * from './components/tree'
export * from './components/tree-select'
export * from './components/upload'

// 兼容老版本
export * from './components/column'
export * from './components/colgroup'
export * from './components/table'
export * from './components/grid'
export * from './components/toolbar'
